import Head from 'next/head'
import Image from 'next/image'
import { Tab } from "@headlessui/react";
import { Inter } from '@next/font/google'
import Masthead from '../components/masthead'
import Aboutus from '../components/aboutus'
import Skills from '../components/skills'
import { fetchCategories } from '../utils/fetchCategories'
import { fetchProducts } from '../utils/fetchProducts'
import { GetServerSideProps } from 'next'
import { urlFor } from '../sanity';
import Productz from '../components/Productz';
import { useState } from 'react';
import Link from 'next/link';
import { Category, Product } from '../typings';

const inter = Inter({ subsets: ['latin'] })

interface Props {
  categories: Category[];
  products: Product[];
}

export default function Home({categories, products }: Props) {

  
  console.log(products);

  const showProducts = (category: number) => {
    return products
      .filter((product) => product.category._ref === categories[category]._id)
      .map((product) => <Productz product={product} key={product._id} />); // filter products by category
  };

  return (
    <div>
      <Head>
        <title>IMR Care-Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Masthead/>
      <Aboutus/>
      <Skills/>
      <Tab.Group>
        <section className=' min-w-fit  gap-y-4 bg-black justify-center  '>
                            <Tab.List className="flex-wrap  bg-black flex gap-y-4  justify-center ">

                    {categories.map((x) => (
                        <Tab
                            key={x.title}
                            id={x.title}
                            className={({ selected }) =>
                                `whitespace-nowrap text-white font-bold font-sans  inline-block rounded-t-lg py-3 px-5 text-sm  outline-none md:py-4 md:px-6 md:text-base ${selected
                                    ? "borderGradient bg-green-300 -100 text-red"
                                    : "border-b-2 border-[#35383C] text-white-400"
                                }`
                            }
                        > 
                        <img className='rounded-full object-fill w-[60px] h-[60px]' src={urlFor(x.image).url()} />
                            {x.title  }
                          
                        </Tab>
                        
                    ))}
                </Tab.List>
                <Tab.Panels className='mx-auto bg-black   max-w-fit  pt-10 pb-24 sm:px-4'>
                  <Tab.Panel className='grid grid-flow-row grid-cols-1 gap-4 gap-y-[80px]  lg:grid lg:grid-flow-row lg:grid-cols-3 lg:gap-4' >{showProducts(0)}</Tab.Panel>
                  <Tab.Panel>{showProducts(1)}</Tab.Panel>
                  <Tab.Panel>{showProducts(2)}</Tab.Panel>
                  <Tab.Panel>{showProducts(3)}</Tab.Panel>
                  <Tab.Panel>{showProducts(4)}</Tab.Panel>
                  <Tab.Panel>{showProducts(5)}</Tab.Panel>
                  <Tab.Panel>{showProducts(6)}</Tab.Panel>
                  <Tab.Panel>{showProducts(7)}</Tab.Panel>

                </Tab.Panels>
                </section>
                </Tab.Group>
                

    </div>
  )
}

export const getServerSideProps: GetServerSideProps<Props> = async (
  context
) => {
  const categories = await fetchCategories();
  const products = await fetchProducts();

  return {
    props: {
      categories,
      products
    },
  };
};